spring:
  data:
    mongodb:
      host: 10.10.1.106
      port: 27017
      database: cpanel_auth_api_test
      field-naming-strategy: org.springframework.data.mapping.model.SnakeCaseFieldNamingStrategy
server:
  port: 8083      